### PR TITLE
install lib_egl

### LINKED ISSUE #246: gh-action broken despite no changes to recipe
All of the tests fail due to failure at importing vtk

```
ERROR: test_vtk_image_resampler (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_vtk_image_resampler
Traceback (most recent call last):
  File "/opt/conda/conda-bld/ccpi-viewer_1653314779193/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/conda/conda-bld/ccpi-viewer_1653314779193/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/opt/conda/conda-bld/ccpi-viewer_1653314779193/test_tmp/Wrappers/Python/test/test_vtk_image_resampler.py", line 1, in <module>
    from ccpi.viewer.utils.conversion import Converter
  File "/opt/conda/conda-bld/ccpi-viewer_1653314779193/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/ccpi/viewer/__init__.py", line 1, in <module>
    from .CILViewer import CILViewer as viewer3D
  File "/opt/conda/conda-bld/ccpi-viewer_1653314779193/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/ccpi/viewer/CILViewer.py", line 22, in <module>
    import vtk
  File "/opt/conda/conda-bld/ccpi-viewer_1653314779193/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/vtk.py", line 31, in <module>
    all_m = importlib.import_module('vtkmodules.all')
  File "/opt/conda/conda-bld/ccpi-viewer_1653314779193/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/conda-bld/ccpi-viewer_1653314779193/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/vtkmodules/all.py", line 23, in <module>
    from .vtkRenderingVtkJS import *
ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
```

### PR DESCRIPTION
**Pull request by lauramurgatroyd**
fixes https://github.com/vais-ral/CILViewer/issues/246
tested here: https://github.com/vais-ral/CILViewer/issues/246

### CODE REVIEW

**Comment by lauramurgatroyd** [comment]
Once merged will release version 1.4.3

**Comment by paskino** [comment]
I think that all the dependencies with GL are for VTK, right?

We could add some parameters to the action, so that we can specify which packages we want; then modify the Dockerfile along these lines

https://stackoverflow.com/a/43656644/1419293

Probably it's a good enhancement.

**Comment by lauramurgatroyd** [comment]
Yes I checked that eqt did not have the same issue

**Comment by lauramurgatroyd** [comment]
replaced by #13

**Pull request closed without merging**
